/**
 * infra/secrets.tf [EXT] + APNs · FCM · JWT keys, rotation
 * config/secrets.js reads these at boot. Key *material* is uploaded once,
 * out of band (never generated by Terraform, never in state) - the
 * lifecycle block below is what keeps `terraform apply` from stomping on a
 * value that was rotated manually or by the rotation Lambda.
 */

resource "aws_secretsmanager_secret" "jwt_keys" {
  name       = "${local.name_prefix}-jwt-keys"
  kms_key_id = aws_kms_key.secrets.arn

  tags = { Name = "${local.name_prefix}-jwt-keys" }
}

resource "aws_secretsmanager_secret_version" "jwt_keys" {
  secret_id     = aws_secretsmanager_secret.jwt_keys.id
  secret_string = jsonencode({ JWT_PRIVATE_KEY = "REPLACE_AFTER_APPLY", JWT_PUBLIC_KEY = "REPLACE_AFTER_APPLY" })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "cookie_secret" {
  name       = "${local.name_prefix}-cookie-secret"
  kms_key_id = aws_kms_key.secrets.arn
}

resource "aws_secretsmanager_secret_version" "cookie_secret" {
  secret_id     = aws_secretsmanager_secret.cookie_secret.id
  secret_string = jsonencode({ COOKIE_SECRET = "REPLACE_AFTER_APPLY" })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "apns_credentials" {
  name       = "${local.name_prefix}-apns-credentials"
  kms_key_id = aws_kms_key.secrets.arn
}

resource "aws_secretsmanager_secret_version" "apns_credentials" {
  secret_id = aws_secretsmanager_secret.apns_credentials.id
  secret_string = jsonencode({
    certificate = var.apns_certificate_pem
    privateKey  = var.apns_private_key_pem
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "fcm_credentials" {
  name       = "${local.name_prefix}-fcm-credentials"
  kms_key_id = aws_kms_key.secrets.arn
}

resource "aws_secretsmanager_secret_version" "fcm_credentials" {
  secret_id     = aws_secretsmanager_secret.fcm_credentials.id
  secret_string = var.fcm_service_account_json

  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "turn_shared_secret" {
  name       = "${local.name_prefix}-turn-shared-secret"
  kms_key_id = aws_kms_key.secrets.arn
}

resource "aws_secretsmanager_secret_version" "turn_shared_secret" {
  secret_id     = aws_secretsmanager_secret.turn_shared_secret.id
  secret_string = var.turn_shared_secret

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# Rotation for the JWT signing key pair: ops/runbooks/rotate-secrets.md walks
# the manual trigger; this schedules the automatic 90-day cadence via a
# rotation Lambda that lives outside this batch (referenced by ARN).
resource "aws_secretsmanager_secret_rotation" "jwt_keys" {
  count               = var.jwt_rotation_lambda_arn == null ? 0 : 1
  secret_id           = aws_secretsmanager_secret.jwt_keys.id
  rotation_lambda_arn = var.jwt_rotation_lambda_arn

  rotation_rules {
    automatically_after_days = 90
  }
}